import houseOne from '../../images/house-1.jpeg';
import houseTwo from '../../images/house-2.jpeg';
import houseThree from '../../images/house-3.jpeg';
import houseFour from '../../images/house-4.jpeg';
import houseFive from '../../images/house-5.jpeg';
import houseSix from '../../images/house-6.jpeg';
const data = {
    listings: [{
        "id": 1,
        "title": "Isolated House",
        "description": "House with a nice garden around",
        "apartment": "Aragon",
        "city": "Sunnywale",
        "state": "California",
        "country": "United States of America",
        "distance": 7,
        "forRent": false,
        "buildingNum": "No.19",
        "streetName": "Powell Lodge",
        "zipCode": "35889",
        "price": 1200,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 2,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 1500,
        "numBaths": 1,
        "numBeds": 3,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 2,
        "title": "Colorful apartment",
        "description": "Apartments with balcony and blue borders",
        "apartment": "Sofi",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 56,
        "forRent": true,
        "buildingNum": "No.89",
        "streetName": "Thomas Parkways",
        "zipCode": "45219",
        "price": 1100,
        "listingStatus": 2,
        "listingType": 3,
        "listingUser": 2,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 2000,
        "numBaths": 4,
        "numBeds": 4,
        "numParkingSpots": 3,
        "petPolicy": false,
        "smokingPolicy": true
    }, {
        "id": 3,
        "title": "Amazing palace",
        "description": "Fully furnished palace",
        "apartment": "Aragon",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 50,
        "forRent": true,
        "buildingNum": "#64",
        "streetName": "Mary Falls",
        "zipCode": "83917",
        "price": 10800,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 1,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 500,
        "numBaths": 4,
        "numBeds": 3,
        "numParkingSpots": 3,
        "petPolicy": true,
        "smokingPolicy": true
    }, {
        "id": 4,
        "title": "Beach side house",
        "description": "A safe home with amazing view of a beach",
        "apartment": "Northpoint",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 77,
        "forRent": false,
        "buildingNum": "#80",
        "streetName": "Hughes Ridge",
        "zipCode": "49268",
        "price": 700,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 4,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 500,
        "numBaths": 3,
        "numBeds": 2,
        "numParkingSpots": 2,
        "petPolicy": false,
        "smokingPolicy": true
    }, {
        "id": 5,
        "title": "Victorian house",
        "description": "Victorian houses with funky colors",
        "apartment": "Southpoint",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 100,
        "forRent": true,
        "buildingNum": "No.92",
        "streetName": "Patrick Haven",
        "zipCode": "44289",
        "price": 8600,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 4,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 1500,
        "numBaths": 1,
        "numBeds": 2,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 6,
        "title": "Serene country-side cottage",
        "description": "Cozy cottage on a hill side",
        "apartment": "Northpoint",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 9,
        "forRent": true,
        "buildingNum": "#12",
        "streetName": "Higgins Lodge",
        "zipCode": "28470",
        "price": 4000,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 5,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 2250,
        "numBaths": 2,
        "numBeds": 1,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 7,
        "title": "House surrounded by plants",
        "description": "House tucked inside a forest",
        "apartment": "Aragon",
        "city": "Sunnywale",
        "state": "California",
        "country": "United States of America",
        "distance": 67,
        "forRent": false,
        "buildingNum": "#26",
        "streetName": "Matthew Via",
        "zipCode": "64062",
        "price": 2200,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 4,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 2250,
        "numBaths": 2,
        "numBeds": 1,
        "numParkingSpots": 2,
        "petPolicy": false,
        "smokingPolicy": true
    }, {
        "id": 8,
        "title": "House with big glass windows",
        "description": "Futuristic glass walled house",
        "apartment": "",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 33,
        "forRent": false,
        "buildingNum": "58",
        "streetName": "Graves Run",
        "zipCode": "35822",
        "price": 11700,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 5,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 500,
        "numBaths": 1,
        "numBeds": 3,
        "numParkingSpots": 3,
        "petPolicy": false,
        "smokingPolicy": true
    }, {
        "id": 9,
        "title": "House on a lake between mountains",
        "description": "Floating house on the lake, with view of mountain",
        "apartment": "Northpoint",
        "city": "Sunnywale",
        "state": "California",
        "country": "United States of America",
        "distance": 49,
        "forRent": true,
        "buildingNum": "No.42",
        "streetName": "Richardson Cove",
        "zipCode": "92206",
        "price": 14700,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 1,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 1000,
        "numBaths": 3,
        "numBeds": 2,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 10,
        "title": "House with a nice pool",
        "description": "House with a nice garden and a pool",
        "apartment": "Northpoint",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 38,
        "forRent": false,
        "buildingNum": "95",
        "streetName": "Evelyn Fall",
        "zipCode": "16959",
        "price": 1050,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 1,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 750,
        "numBaths": 2,
        "numBeds": 4,
        "numParkingSpots": 1,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 11,
        "title": "House with a hill-side view",
        "description": "House on a hill side with a nice pool",
        "apartment": "Aragon",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 20,
        "forRent": false,
        "buildingNum": "#41",
        "streetName": "Kelley Loop",
        "zipCode": "81691",
        "price": 4200,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 5,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 4000,
        "numBaths": 3,
        "numBeds": 3,
        "numParkingSpots": 1,
        "petPolicy": false,
        "smokingPolicy": true
    }, {
        "id": 12,
        "title": "House on a lake",
        "description": "Lake house, ideal for horror movies",
        "apartment": "Aragon",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 76,
        "forRent": false,
        "buildingNum": "81",
        "streetName": "Jeffrey Viaduct",
        "zipCode": "49327",
        "price": 10200,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 2,
        "listingView": 0,
        "furnished": true,
        "squareFeet": 1000,
        "numBaths": 4,
        "numBeds": 2,
        "numParkingSpots": 1,
        "petPolicy": true,
        "smokingPolicy": true
    }, {
        "id": 13,
        "title": "Simple house",
        "description": "Simple house, ready to move in",
        "apartment": "Northpoint",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "distance": 86,
        "forRent": false,
        "buildingNum": "#23",
        "streetName": "John Union",
        "zipCode": "03181",
        "price": 3200,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 5,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 3000,
        "numBaths": 4,
        "numBeds": 3,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": true
    }, {
        "id": 14,
        "title": "Cozy house beside a lake",
        "description": "Cozy house in a cold climate beside the lake",
        "apartment": "Northpoint",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 23,
        "forRent": false,
        "buildingNum": "No.68",
        "streetName": "Wells Trail",
        "zipCode": "31157",
        "price": 10000,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 1,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 750,
        "numBaths": 3,
        "numBeds": 1,
        "numParkingSpots": 3,
        "petPolicy": true,
        "smokingPolicy": false
    }, {
        "id": 15,
        "title": "Moroccan house",
        "description": "Clean and simple architecture",
        "apartment": "Northpoint",
        "city": "Sunnywale",
        "state": "California",
        "country": "United States of America",
        "distance": 70,
        "forRent": false,
        "buildingNum": "#12",
        "streetName": "Patterson Canyon",
        "zipCode": "20087",
        "price": 5600,
        "listingStatus": 2,
        "listingType": 1,
        "listingUser": 3,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 2000,
        "numBaths": 1,
        "numBeds": 2,
        "numParkingSpots": 3,
        "petPolicy": true,
        "smokingPolicy": true
    }, {
        "id": 16,
        "title": "Condo on the corner",
        "description": "On the corner, closer to everything",
        "apartment": "Southpoint",
        "city": "San Jose",
        "state": "California",
        "country": "United States of America",
        "distance": 14,
        "forRent": true,
        "buildingNum": "No.16",
        "streetName": "Aguilar Mews",
        "zipCode": "12981",
        "price": 2700,
        "listingStatus": 2,
        "listingType": 2,
        "listingUser": 2,
        "listingView": 0,
        "furnished": false,
        "squareFeet": 1000,
        "numBaths": 1,
        "numBeds": 4,
        "numParkingSpots": 2,
        "petPolicy": true,
        "smokingPolicy": false
    }
]

};

export default data;